version: "3"

services:
  backend:
    build: .
    container_name: softeo_api
    tty: true
    stdin_open: true
    restart: always
    volumes: 
      - .:/app
    environment:
      DATABASE_URL: mysql://root:password@db:3306/softeo_db?schema=public
    depends_on:
      - db
    ports:
      - 3001:3001
  db:
    container_name: softeo_db
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always