on:
  pull_request:
    types: [opened, synchronize]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.6
        with:
          node-version: '16'
      - run: npm install
      - run: npx eslint .
